// Centralized mock data matching the exact mentor prompt specifications
// Location context: Jalandhar, Punjab & neighboring hubs (Ludhiana, Amritsar, Chandigarh, Phagwara, Delhi)

export const LOCATIONS = [
  'Jalandhar, Punjab',
  'Model Town, Jalandhar',
  'Civil Lines, Jalandhar',
  'Ludhiana, Punjab',
  'Amritsar, Punjab',
  'Chandigarh, Tri-City',
  'Phagwara, Punjab',
  'Delhi, NCR',
];

export const CURRENT_USER = {
  id: 'user_ritvik',
  name: 'Ritvik Verma',
  username: 'ritvik',
  location: 'Jalandhar, Punjab',
  title: 'Community Builder & Changemaker',
  bio: 'Interested in education, youth digital literacy, technology, and grassroots environmental action in Punjab.',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
  banner: 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?w=1200&auto=format&fit=crop&q=80',
  followersCount: 1240,
  followingCount: 486,
  activitiesCount: 38,
  volunteerHours: 38,
  impactScore: 742,
  causesCount: 4,
  badges: [
    { id: 'b1', name: 'First Activity', icon: '🌱', date: 'Jan 2026' },
    { id: 'b2', name: 'Community Contributor', icon: '🤝', date: 'Feb 2026' },
    { id: 'b3', name: '50 Impact Hours', icon: '❤️', date: 'Mar 2026' },
    { id: 'b4', name: 'Environment Supporter', icon: '🌏', date: 'Apr 2026' },
    { id: 'b5', name: 'Community Builder', icon: '🏆', date: 'May 2026' },
  ],
};

export const DEMO_USERS = [
  {
    id: 'u_aisha',
    name: 'Aisha Sharma',
    username: 'aisha_s',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&auto=format&fit=crop&q=80',
    location: 'Jalandhar, Punjab',
    role: 'Active Volunteer',
    bio: 'Animal welfare and weekend community food drives advocate.',
    isFollowing: true,
  },
  {
    id: 'u_rahul',
    name: 'Rahul Mehta',
    username: 'rahul_m',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    location: 'Model Town, Jalandhar',
    role: 'Student Mentor',
    bio: 'Coding tutor for underserved high school students.',
    isFollowing: false,
  },
  {
    id: 'u_simran',
    name: 'Simran Kaur',
    username: 'simran_k',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=300&auto=format&fit=crop&q=80',
    location: 'Amritsar, Punjab',
    role: 'Community Health Lead',
    bio: 'Organizing blood donation drives and maternal care workshops.',
    isFollowing: false,
  },
  {
    id: 'u_arjun',
    name: 'Arjun Kapoor',
    username: 'arjun_k',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
    location: 'Ludhiana, Punjab',
    role: 'Eco Activist',
    bio: 'Micro-forest enthusiast and urban farmer.',
    isFollowing: true,
  },
  {
    id: 'u_priya',
    name: 'Priya Mehta',
    username: 'priya_m',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=300&auto=format&fit=crop&q=80',
    location: 'Chandigarh, Tri-City',
    role: 'NGO Coordinator',
    bio: 'Bridging corporate volunteers with grassroots non-profits.',
    isFollowing: false,
  },
];

export const DEMO_ORGANIZATIONS = [
  {
    id: 'org_green_punjab',
    name: 'Green Punjab Initiative',
    handle: '@greenpunjab',
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=300&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=1200&auto=format&fit=crop&q=80',
    location: 'Jalandhar, Punjab',
    category: 'Environment',
    mission: 'Working toward greener cities through mass tree plantations, canal restorations, and clean air campaigns.',
    followersCount: '1.8K',
    volunteersEngaged: 850,
    impactHours: 3200,
    isFollowing: true,
  },
  {
    id: 'org_helping_hands',
    name: 'Helping Hands Foundation',
    handle: '@helpinghands_pb',
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=300&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?w=1200&auto=format&fit=crop&q=80',
    location: 'Model Town, Jalandhar',
    category: 'Food Security & Relief',
    mission: 'Eliminating local hunger through community pantries, food rescue, and dignified daily nourishment drives.',
    followersCount: '2.4K',
    volunteersEngaged: 1120,
    impactHours: 4900,
    isFollowing: false,
  },
  {
    id: 'org_sevaconnect',
    name: 'SevaConnect Punjab',
    handle: '@sevaconnect',
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?w=300&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1532629345422-7515f3d16bb6?w=1200&auto=format&fit=crop&q=80',
    location: 'Ludhiana, Punjab',
    category: 'Community Aid',
    mission: 'Coordinating emergency relief, elderly healthcare companions, and winter blanket distributions.',
    followersCount: '3.1K',
    volunteersEngaged: 1400,
    impactHours: 6100,
    isFollowing: false,
  },
  {
    id: 'org_youth_change',
    name: 'Youth For Change',
    handle: '@youthforchange',
    verified: false,
    avatar: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=300&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1526976668912-1a811878dd37?w=1200&auto=format&fit=crop&q=80',
    location: 'Amritsar, Punjab',
    category: 'Youth & Education',
    mission: 'Mobilizing college students for slum schooling, digital literacy, and women self-defense workshops.',
    followersCount: '1.2K',
    volunteersEngaged: 630,
    impactHours: 2400,
    isFollowing: true,
  },
  {
    id: 'org_edu_for_all',
    name: 'Education For All',
    handle: '@educationforall',
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=300&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=1200&auto=format&fit=crop&q=80',
    location: 'Chandigarh, Tri-City',
    category: 'Education',
    mission: 'Ensuring every child in Punjab has access to books, basic computing skills, and after-school tutoring.',
    followersCount: '2.9K',
    volunteersEngaged: 980,
    impactHours: 4100,
    isFollowing: false,
  },
  {
    id: 'org_paws_care',
    name: 'Paws & Care Foundation',
    handle: '@pawscare_pb',
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=300&auto=format&fit=crop&q=80',
    banner: 'https://images.unsplash.com/photo-1535268647677-300dbf3d78d1?w=1200&auto=format&fit=crop&q=80',
    location: 'Jalandhar, Punjab',
    category: 'Animal Welfare',
    mission: 'Street animal rescue, rabies vaccination camps, and foster matching across Jalandhar and Phagwara.',
    followersCount: '1.6K',
    volunteersEngaged: 420,
    impactHours: 1950,
    isFollowing: true,
  },
];

export const DEMO_COMMUNITIES = [
  {
    id: 'comm_eco_jalandhar',
    slug: 'environmental-volunteers-jalandhar',
    name: 'Environmental Volunteers — Jalandhar',
    membersCount: 12400,
    membersDisplay: '12.4K',
    icon: '🌱',
    category: 'Environment',
    description: 'People working together to make Jalandhar greener through urban afforestation, clean-up walks, and waste segregation.',
    coverImage: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=1000&auto=format&fit=crop&q=80',
    recentActivity: '32 people joined Tree Plantation Drive',
    upcomingEventsCount: 3,
    serviceProjectsCount: 8,
    isJoined: true,
    location: 'Jalandhar, Punjab',
  },
  {
    id: 'comm_students_change',
    slug: 'students-for-change',
    name: 'Students for Change',
    membersCount: 8700,
    membersDisplay: '8.7K',
    icon: '📚',
    category: 'Education & Youth',
    description: 'High school and university youth connecting for weekend tutoring, career mentorship, and educational drives.',
    coverImage: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=1000&auto=format&fit=crop&q=80',
    recentActivity: 'Shared digital literacy resources for 4 schools',
    upcomingEventsCount: 2,
    serviceProjectsCount: 5,
    isJoined: false,
    location: 'Jalandhar & Phagwara',
  },
  {
    id: 'comm_animal_lovers',
    slug: 'animal-lovers-punjab',
    name: 'Animal Lovers Punjab',
    membersCount: 6200,
    membersDisplay: '6.2K',
    icon: '🐾',
    category: 'Animal Welfare',
    description: 'Community network feeding stray dogs, reporting injured animals, and coordinating volunteer foster homes.',
    coverImage: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=1000&auto=format&fit=crop&q=80',
    recentActivity: 'Rescued 14 street puppies this month',
    upcomingEventsCount: 1,
    serviceProjectsCount: 4,
    isJoined: true,
    location: 'Jalandhar & Ludhiana',
  },
  {
    id: 'comm_blood_donors',
    slug: 'blood-donor-network',
    name: 'Blood Donor Network Punjab',
    membersCount: 15300,
    membersDisplay: '15.3K',
    icon: '❤️',
    category: 'Healthcare',
    description: 'Emergency urgent blood and platelet matching hub connecting verified donors with local hospitals 24/7.',
    coverImage: 'https://images.unsplash.com/photo-1615461066841-6116e61058f4?w=1000&auto=format&fit=crop&q=80',
    recentActivity: 'Fulfilled 28 emergency requests this week',
    upcomingEventsCount: 2,
    serviceProjectsCount: 6,
    isJoined: false,
    location: 'Punjab State-wide',
  },
  {
    id: 'comm_model_town',
    slug: 'model-town-community',
    name: 'Model Town Neighborhood Watch & Care',
    membersCount: 9800,
    membersDisplay: '9.8K',
    icon: '🏘️',
    category: 'Local Neighborhood',
    description: 'Residents of Model Town Jalandhar discussing civic repairs, park maintenance, senior citizen assistance, and safety.',
    coverImage: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=1000&auto=format&fit=crop&q=80',
    recentActivity: 'Organized neighborhood solar light petition',
    upcomingEventsCount: 1,
    serviceProjectsCount: 3,
    isJoined: true,
    location: 'Model Town, Jalandhar',
  },
  {
    id: 'comm_creative_volunteers',
    slug: 'creative-volunteers',
    name: 'Creative Volunteers & Designers',
    membersCount: 4100,
    membersDisplay: '4.1K',
    icon: '🎨',
    category: 'Creative Support',
    description: 'Designers, writers, video editors, and photographers offering pro-bono creative help for grassroots social causes.',
    coverImage: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=1000&auto=format&fit=crop&q=80',
    recentActivity: 'Created 6 campaign posters for NGO tree drives',
    upcomingEventsCount: 2,
    serviceProjectsCount: 7,
    isJoined: false,
    location: 'Remote / All Punjab',
  },
];

export const TRENDING_TOPICS = [
  { tag: 'CleanJalandhar', postsCount: '1.4K posts', trendingRank: '1', badge: '🔥 Trending Local' },
  { tag: 'TreePlantation', postsCount: '890 posts', trendingRank: '2', badge: '🌱 Top Cause' },
  { tag: 'BloodDonation', postsCount: '720 posts', trendingRank: '3', badge: '❤️ Emergency' },
  { tag: 'YouthForChange', postsCount: '640 posts', trendingRank: '4', badge: '⚡ Youth Voice' },
  { tag: 'CommunityCleanup', postsCount: '510 posts', trendingRank: '5', badge: '🧹 Action' },
  { tag: 'EducationForAll', postsCount: '430 posts', trendingRank: '6', badge: '📚 Mentorship' },
];

export const COMMUNITY_NEEDS = [
  {
    id: 'need_1',
    type: 'request',
    urgency: 'high',
    title: 'Volunteers urgently needed for weekend food distribution',
    organization: 'Helping Hands Foundation',
    location: 'Model Town, Jalandhar',
    spotsRemaining: 8,
    date: 'Saturday · 10:00 AM',
    tags: ['Food Relief', 'Weekend'],
  },
  {
    id: 'need_2',
    type: 'request',
    urgency: 'medium',
    title: 'Graphic designer needed for upcoming Punjab clean air campaign',
    organization: 'Green Punjab Initiative',
    location: 'Remote / Jalandhar',
    spotsRemaining: 2,
    date: 'Flexible schedule',
    tags: ['Pro-bono Design', 'Environment'],
  },
  {
    id: 'need_3',
    type: 'request',
    urgency: 'medium',
    title: 'Weekend tutors needed for primary school math & English',
    organization: 'Education For All',
    location: 'Civil Lines, Jalandhar',
    spotsRemaining: 6,
    date: 'Sundays · 9:00 AM',
    tags: ['Tutoring', 'Youth'],
  },
  {
    id: 'need_4',
    type: 'request',
    urgency: 'high',
    title: 'Foster support needed for 3 rescued puppies during monsoon',
    organization: 'Paws & Care Foundation',
    location: 'Jalandhar',
    spotsRemaining: 3,
    date: 'Immediate · 2 weeks foster',
    tags: ['Animal Rescue', 'Foster'],
  },
];

export const DEMO_POSTS = [
  {
    id: 'post_1',
    author: {
      name: 'Aisha Sharma',
      username: 'aisha_s',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&auto=format&fit=crop&q=80',
      isVerified: false,
      badge: 'Community Volunteer',
    },
    location: 'Jalandhar, Punjab',
    timestamp: '2h ago',
    content: "Spent my Saturday volunteering at a local food distribution drive with Helping Hands! Seeing everyone come together to pack 400 ration kits was amazing! ❤️ Join in next week if you have two free hours.",
    image: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=1000&auto=format&fit=crop&q=80',
    tags: ['CleanJalandhar', 'CommunityFirst', 'Volunteering'],
    likesCount: 128,
    commentsCount: 24,
    sharesCount: 12,
    isLiked: false,
    isBookmarked: false,
    postType: 'social',
  },
  {
    id: 'post_2',
    author: {
      name: 'Green Punjab Initiative',
      username: 'greenpunjab',
      avatar: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=300&auto=format&fit=crop&q=80',
      isVerified: true,
      badge: 'Verified NGO',
    },
    location: 'Jalandhar, Punjab',
    timestamp: '4h ago',
    content: "We're organizing a massive Tree Plantation Drive this Sunday at the Cantonment Green Corridor! We need 20 more passionate volunteers to help us plant 350 native saplings. Gloves, tools, and refreshments provided 🌱",
    image: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=1000&auto=format&fit=crop&q=80',
    tags: ['TreePlantation', 'Environment', 'CleanPunjab'],
    likesCount: 86,
    commentsCount: 14,
    sharesCount: 32,
    isLiked: true,
    isBookmarked: true,
    postType: 'opportunity_integrated',
    opportunityData: {
      id: 'opp_tree_drive',
      title: 'Tree Plantation Drive',
      category: 'Environment',
      date: 'Sunday · 8:00 AM',
      location: 'Cantonment Green Corridor, Jalandhar',
      hoursGranted: 4,
      spotsRemaining: 18,
      participantsCount: 32,
      isJoined: false,
    },
  },
  {
    id: 'post_3',
    author: {
      name: 'Rahul Mehta',
      username: 'rahul_m',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
      isVerified: false,
      badge: 'Student Mentor',
    },
    location: 'Model Town, Jalandhar',
    timestamp: '5h ago',
    content: "Does anyone know of local community centers or non-profits helping middle school students with digital literacy? Our college volunteer club has 8 donated laptops and 10 student mentors ready to teach basic Python and web navigation!",
    tags: ['EducationForAll', 'YouthForChange'],
    likesCount: 54,
    commentsCount: 31,
    sharesCount: 8,
    isLiked: false,
    isBookmarked: false,
    postType: 'discussion',
  },
  {
    id: 'post_4',
    author: {
      name: 'Helping Hands Foundation',
      username: 'helpinghands_pb',
      avatar: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=300&auto=format&fit=crop&q=80',
      isVerified: true,
      badge: 'Verified NGO',
    },
    location: 'Jalandhar, Punjab',
    timestamp: '6h ago',
    content: "✨ Community Milestone: 120 nutritious meals and 45 fresh fruit crates distributed this weekend across Old Railway Road settlement! Thank you to our 16 volunteer helpers!",
    image: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?w=1000&auto=format&fit=crop&q=80',
    tags: ['CleanJalandhar', 'FoodSecurity'],
    likesCount: 214,
    commentsCount: 19,
    sharesCount: 45,
    isLiked: true,
    isBookmarked: false,
    postType: 'impact_update',
  },
  {
    id: 'post_5',
    author: {
      name: 'Ritvik Verma',
      username: 'ritvik',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
      isVerified: false,
      badge: 'Community Builder',
    },
    location: 'Jalandhar, Punjab',
    timestamp: '1d ago',
    content: "Just completed 5 hours of volunteering with Food Distribution Drive! 🍲 Nothing beats the feeling of giving back to our neighborhood with such a kind team.",
    image: 'https://images.unsplash.com/photo-1578357078586-491adf1aa5ba?w=1000&auto=format&fit=crop&q=80',
    tags: ['CommunityImpact', '5HoursLogged'],
    likesCount: 94,
    commentsCount: 8,
    sharesCount: 5,
    isLiked: true,
    isBookmarked: false,
    postType: 'impact_celebration',
    celebrationData: {
      hours: 5,
      activityTitle: 'Food Distribution Drive',
      badge: 'Community Contributor',
    }
  },
];

export const DEMO_OPPORTUNITIES = [
  {
    id: 'opp_1',
    title: 'Community Park Cleanup & Micro-Garden Setup',
    organization: 'Green Punjab Initiative',
    orgVerified: true,
    category: 'Environment',
    location: 'Model Town Park, Jalandhar',
    date: 'This Saturday, 7:30 AM',
    time: '7:30 AM – 11:30 AM',
    hoursGranted: 4,
    spotsRemaining: 12,
    totalSpots: 30,
    participantsCount: 18,
    coverImage: 'https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?w=800&auto=format&fit=crop&q=80',
    description: 'Join local neighbors to clean discarded plastic waste, plant flowering shrubs, and build composting bins at Model Town public park.',
    skills: ['No prior experience', 'Teamwork', 'Gardening'],
    isJoined: false,
  },
  {
    id: 'opp_2',
    title: 'Weekend Food Rescue & Meal Packaging',
    organization: 'Helping Hands Foundation',
    orgVerified: true,
    category: 'Food',
    location: 'Civil Hospital Road, Jalandhar',
    date: 'Sunday, 9:00 AM',
    time: '9:00 AM – 1:00 PM',
    hoursGranted: 4,
    spotsRemaining: 7,
    totalSpots: 25,
    participantsCount: 18,
    coverImage: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?w=800&auto=format&fit=crop&q=80',
    description: 'Sort donated produce, pack nutritional meal kits, and support logistics for 3 local underserved daycare communities.',
    skills: ['Food handling', 'Packing', 'Empathy'],
    isJoined: true,
  },
  {
    id: 'opp_3',
    title: 'Digital Skills & Smartphone Workshop for Seniors',
    organization: 'Students for Change',
    orgVerified: false,
    category: 'Education',
    location: 'Urban Community Hall, Jalandhar',
    date: 'Saturday, 3:00 PM',
    time: '3:00 PM – 6:00 PM',
    hoursGranted: 3,
    spotsRemaining: 5,
    totalSpots: 15,
    participantsCount: 10,
    coverImage: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&auto=format&fit=crop&q=80',
    description: 'Sit 1-on-1 with senior citizens to guide them on using digital health apps, UPI payments, cyber scam prevention, and video calling families.',
    skills: ['Patience', 'Basic Tech', 'Hindi/Punjabi speaking'],
    isJoined: false,
  },
  {
    id: 'opp_4',
    title: 'Street Dog Vaccination & Medical Checkup Camp',
    organization: 'Paws & Care Foundation',
    orgVerified: true,
    category: 'Animals',
    location: 'Near BMC Chowk, Jalandhar',
    date: 'Next Sunday, 8:00 AM',
    time: '8:00 AM – 12:00 PM',
    hoursGranted: 4,
    spotsRemaining: 9,
    totalSpots: 20,
    participantsCount: 11,
    coverImage: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=800&auto=format&fit=crop&q=80',
    description: 'Assist licensed veterinarians with gentle pet restraint, recording vaccination charts, and distributing collar reflectors.',
    skills: ['Comfortable with dogs', 'Record keeping'],
    isJoined: false,
  },
  {
    id: 'opp_5',
    title: 'Blood Donation Camp & Donor Registration',
    organization: 'Blood Donor Network Punjab',
    orgVerified: true,
    category: 'Healthcare',
    location: 'Red Cross Bhawan, Jalandhar',
    date: 'Friday, 10:00 AM',
    time: '10:00 AM – 4:00 PM',
    hoursGranted: 6,
    spotsRemaining: 15,
    totalSpots: 40,
    participantsCount: 25,
    coverImage: 'https://images.unsplash.com/photo-1615461066841-6116e61058f4?w=800&auto=format&fit=crop&q=80',
    description: 'Help register prospective donors, assist nurse stations with post-donation juice distribution, and issue donor recognition certificates.',
    skills: ['Hospitality', 'Compassion'],
    isJoined: false,
  },
  {
    id: 'opp_6',
    title: 'Slum Children Reading Circles & Storytelling',
    organization: 'Education For All',
    orgVerified: true,
    category: 'Education',
    location: 'Basti Sheikh, Jalandhar',
    date: 'Sunday, 10:30 AM',
    time: '10:30 AM – 1:30 PM',
    hoursGranted: 3,
    spotsRemaining: 6,
    totalSpots: 16,
    participantsCount: 10,
    coverImage: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800&auto=format&fit=crop&q=80',
    description: 'Read colorful bilingual storybooks with 25 primary school children, conduct interactive drawing games, and distribute notebook kits.',
    skills: ['Storytelling', 'Enthusiasm', 'Creative games'],
    isJoined: false,
  },
  {
    id: 'opp_7',
    title: 'Canal Bank Plastic Cleanup Walk',
    organization: 'Green Punjab Initiative',
    orgVerified: true,
    category: 'Environment',
    location: 'Bist Doab Canal Trail, Jalandhar',
    date: 'Saturday, 6:30 AM',
    time: '6:30 AM – 9:30 AM',
    hoursGranted: 3,
    spotsRemaining: 22,
    totalSpots: 50,
    participantsCount: 28,
    coverImage: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=800&auto=format&fit=crop&q=80',
    description: 'A morning walking cleanup removing non-biodegradable waste along a 2 km stretch of the scenic Bist Doab canal.',
    skills: ['Walking fitness', 'Eco awareness'],
    isJoined: false,
  },
  {
    id: 'opp_8',
    title: 'Senior Citizen Recreation & Board Games Day',
    organization: 'SevaConnect Punjab',
    orgVerified: true,
    category: 'Elderly',
    location: 'Golden Age Home, Model Town',
    date: 'Sunday, 4:00 PM',
    time: '4:00 PM – 7:00 PM',
    hoursGranted: 3,
    spotsRemaining: 4,
    totalSpots: 12,
    participantsCount: 8,
    coverImage: 'https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=800&auto=format&fit=crop&q=80',
    description: 'Spend an afternoon playing carrom, chess, sharing nostalgic music, and bringing festive warmth to elder residents.',
    skills: ['Friendly listening', 'Music/Chess'],
    isJoined: false,
  },
  {
    id: 'opp_9',
    title: 'Monsoon Flood Relief Readiness Drill & Kit Packing',
    organization: 'SevaConnect Punjab',
    orgVerified: true,
    category: 'Disaster Relief',
    location: 'Disaster Cell, Jalandhar',
    date: 'Saturday, 11:00 AM',
    time: '11:00 AM – 3:00 PM',
    hoursGranted: 4,
    spotsRemaining: 14,
    totalSpots: 35,
    participantsCount: 21,
    coverImage: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?w=800&auto=format&fit=crop&q=80',
    description: 'Assembly of emergency water purification tablets, dry rations, and basic first aid kits for vulnerable low-lying river areas.',
    skills: ['Physical packing', 'Fast-paced execution'],
    isJoined: false,
  },
  {
    id: 'opp_10',
    title: 'Community Mural Painting: "Green & Healthy Jalandhar"',
    organization: 'Creative Volunteers',
    orgVerified: false,
    category: 'Community',
    location: 'Flyover Underpass, Rama Mandi',
    date: 'Sunday, 8:00 AM',
    time: '8:00 AM – 1:00 PM',
    hoursGranted: 5,
    spotsRemaining: 10,
    totalSpots: 25,
    participantsCount: 15,
    coverImage: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800&auto=format&fit=crop&q=80',
    description: 'Transform drab city walls with uplifting murals depicting environmental sustainability, cycling paths, and educational hope.',
    skills: ['Painting/Sketching', 'Enthusiastic beginners welcome'],
    isJoined: false,
  },
];

export const DEMO_REVIEWS = [
  {
    id: 'rev_1',
    author: 'Aarav Sharma',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200&auto=format&fit=crop&q=80',
    location: 'Jalandhar, Punjab',
    quote: "ConnectServe helped me discover people in my city who genuinely care about the same causes. It feels like a real social network with actual positive real-world action.",
    activity: 'Tree Plantation & Park Cleanup',
    rating: 5,
  },
  {
    id: 'rev_2',
    author: 'Simran Kaur',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&auto=format&fit=crop&q=80',
    location: 'Amritsar, Punjab',
    quote: "I love being able to see what's happening around my community and actually participate with two taps. The social feed makes volunteering feel celebratory!",
    activity: 'Blood Donation Coordinator',
    rating: 5,
  },
  {
    id: 'rev_3',
    author: 'Priya Mehta',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=200&auto=format&fit=crop&q=80',
    location: 'Model Town, Jalandhar',
    quote: "Posting our community events on ConnectServe helped our non-profit reach 4x more volunteers than traditional social media. Truly a game changer.",
    activity: 'NGO Partner Lead',
    rating: 5,
  },
  {
    id: 'rev_4',
    author: 'Harpreet Singh',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&auto=format&fit=crop&q=80',
    location: 'Ludhiana, Punjab',
    quote: "As a college student, earning verifiable service certificates while networking with local mentors gave my resume and my weekends real meaning.",
    activity: 'Digital Literacy Tutor',
    rating: 5,
  },
  {
    id: 'rev_5',
    author: 'Kavita Joshi',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&auto=format&fit=crop&q=80',
    location: 'Chandigarh',
    quote: "The interactive map and localized community groups make it easy to spot neighborhood cleanups within walking distance of my house.",
    activity: 'Canal Trail Cleaner',
    rating: 5,
  },
  {
    id: 'rev_6',
    author: 'Manish Verma',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    location: 'Phagwara, Punjab',
    quote: "No boring administration paperwork. Just vibrant community discussions, passionate local leaders, and direct ways to lend a helping hand.",
    activity: 'Elderly Home Volunteer',
    rating: 5,
  },
];

export const DEMO_COMMUNITY_IMPACT = {
  totalVolunteers: 12480,
  volunteerHours: 42810,
  communityActivities: 1284,
  peopleReached: 85240,
  treesPlanted: 18450,
  mealsDistributed: 64200,
};

export const MAP_MARKERS = [
  { id: 'm1', name: 'Model Town Park Clean-up', category: 'Environment', lat: 31.312, lng: 75.584, address: 'Model Town, Jalandhar', participants: 32 },
  { id: 'm2', name: 'Free Ration Distribution Center', category: 'Food', lat: 31.325, lng: 75.572, address: 'Railway Road, Jalandhar', participants: 18 },
  { id: 'm3', name: 'Youth Digital Literacy Lab', category: 'Education', lat: 31.332, lng: 75.590, address: 'Civil Lines, Jalandhar', participants: 14 },
  { id: 'm4', name: 'Community Health & Blood Camp', category: 'Healthcare', lat: 31.305, lng: 75.568, address: 'BMC Chowk, Jalandhar', participants: 42 },
  { id: 'm5', name: 'Stray Animal Shelter & Care', category: 'Animals', lat: 31.340, lng: 75.602, address: 'Rama Mandi, Jalandhar', participants: 12 },
];
